[package]
name = "norg-linter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
rust-norg = { git = "https://github.com/hardfau1t/rust-norg.git", version = "0.1.0" }
